// Generated by AI, of course

// based on above data, export an interface for this
export interface VtbMoeListResponse {
    meta: {
        UUID_NAMESPACE: string
        linkSyntax: {
            [key: string]: string
        }
        timestamp: number
    }
    vtbs: VtbMoeVtbResponse[]
}


export interface VtbMoeVtbResponse {
    uuid: string
    type: string
    bot: boolean
    accounts: {
        id: string
        type: string
        platform: string
    }[]
    name: {
        extra: any[]
        cn: string
        default: string
    }
}

export interface VtbMoeDetailResponse {
    mid: number
    uuid: string
    uname: string
    video: number
    roomid: number
    sign: string
    notice: string
    face: string
    rise: number
    topPhoto: string
    archiveView: number
    follower: number
    liveStatus: number
    recordNum: number
    guardNum: number
    lastLive: any
    guardChange: number
    guardType: number[]
    online: number
    title: string
    time: number
    liveStartTime: number
}