console.info = console.info.bind(console, '[bilibili-vup-stream-enhancer]')
console.warn = console.warn.bind(console, '[bilibili-vup-stream-enhancer]')
console.error = console.error.bind(console, '[bilibili-vup-stream-enhancer]')
console.log = console.log.bind(console, '[bilibili-vup-stream-enhancer]')
console.debug = process.env.NODE_ENV === 'production' ? () => {} : console.debug.bind(console, '[bilibili-vup-stream-enhancer]')
console.trace = process.env.NODE_ENV === 'production' ? () => {} : console.trace.bind(console, '[bilibili-vup-stream-enhancer]')